=== ashmita-12/Web-development/Ashmita 28360  web technology lab report/Labwork_Ashmita/lab 4.3.dtd
<!ELEMENT Books (Book+)>
<!ELEMENT Book (Name, Author+, PageNo, Price)>
<!ATTLIST Book
    isbn CDATA #REQUIRED>

<!ELEMENT Name (FirstName, MiddleName?, LastName)>
<!ELEMENT FirstName (#PCDATA)>
<!ELEMENT MiddleName (#PCDATA)>
<!ELEMENT LastName (#PCDATA)>

<!ELEMENT Author (#PCDATA)>

<!ELEMENT PageNo (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
<!ATTLIST Price 
    max CDATA #FIXED "1000">

=== ashmita-12/Web-development/Ashmita 28360  web technology lab report/Labwork_Ashmita/lab 4.3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Books SYSTEM "lab 4.3.dtd">
<?xml-stylesheet type="text/xsl" href="lab 4.3.xsl"?>
<Books>
    <Book isbn="978-3-16-148410-0">
        <Name>
            <FirstName>Ashmita</FirstName>
            <LastName>Dahal</LastName>
        </Name>
        <Author>Jane Smith</Author>
        <Author>Emily Johnson</Author>
        <PageNo>320</PageNo>
        <Price max="1000">950</Price>
    </Book>
    <Book isbn="978-1-23-456789-7">
        <Name>
            <FirstName>Anna</FirstName>
            <LastName>Brown</LastName>
        </Name>
        <Author>George Martin</Author>
        <PageNo>450</PageNo>
        <Price max="1000">850</Price>
    </Book>
</Books>
